#!/bin/bash

# Package redash report dashboard
# $1 is the slug, $2 is the real name
mkdir packdir
cd packdir
python ../redash-extract/redash-extract-dash.py  $1 "noTarkGRudp4BWpNfDezNL1mSnBs0g4Mnn4WVjvK"

mv */*.json .
tar -cvf ../$1.tar *
cd ..
rm -r packdir
echo $2 Dashboard prepared as $1.tar
